# Generated by Django 4.2.2 on 2023-06-17 10:40

import django.core.validators
from django.db import migrations, models
import transcription_webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=transcription_webapp.models.unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'mp4'])])),
            ],
        ),
    ]
