# Generated by Django 4.2.2 on 2023-06-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='transcript',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
